# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - va-ede-healthbot-web-dev-decision

on:
  push:
    branches:
      - dev-decision

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v1
      with:
        app-name: 'va-ede-healthbot-web-dev-decision'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_2467f90b83914bddbf944ccba32286a5 }}
        package: .